version: '3'

services:
  frontend:
    build: .
    command: ['/bin/sh', '-c', 'cd /usr/src/frontend && npm run dev']
    volumes:
      - ./frontend:/usr/src/frontend:delegated
      - node_modules:/usr/src/frontend/node_modules
    working_dir: /usr/src/frontend
    ports:
      - 8080:8080
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=8000
      - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules:
